version: '3.8'

services:
  postgres:
    image: postgres
    container_name: project-ai-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - project-ai-network

  localstack:
    container_name: project-ai-localstack-s3
    image: localstack/localstack:3.3.0
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=sa-east-1
      - SERVICES=s3
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./create-s3-bucket.sh:/etc/localstack/init/ready.d/create-s3-bucket.sh"

networks:
  project-ai-network:

volumes:
  project-ai-volume:
