version: '3.8'

services:
  postgres:
    image: postgres
    container_name: project-ai-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - project-ai-network

networks:
  project-ai-network:

volumes:
  project-ai-volume:
